# Generated by Django 3.1 on 2020-11-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieimage',
            name='images',
            field=models.ImageField(upload_to='./'),
        ),
    ]
